#Setup the cognito user pool and application client
Resources:
  TestUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: test-user-pool
      Schema:
        - Mutable: false
          Name: email
          Required: true
        - Mutable: false
          Name: name
          Required: true
      AutoVerifiedAttributes: [email]
  TestAppClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: test-app-client
      UserPoolId: !Ref TestUserPool
  TestAPIRole:
    Type: AWS::IAM::Role
    Properties: 
      RoleName: test-api-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action: 
              - sts:AssumeRole
  TestAPIPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: test-api-policy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - lambda:invokeFunction
            Resource:
              - "*"
      Roles: [{Ref : TestAPIRole}]
  TestAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: test-api
      Description: API use for parking info
      FailOnWarnings: true
  TestAPIAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: test-api-authorizer
      RestApiId: !Ref TestAPI
      IdentitySource: method.request.header.Authorization
      Type: COGNITO_USER_POOLS
      ProviderARNs: ["arn:aws:cognito-idp:us-west-2:082880322489:userpool/us-west-2_c9xtJ9FZz"]
  TestAPIResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref TestAPI
      ParentId: {"Fn::GetAtt": [TestAPI, RootResourceId]}
      PathPart: parking
  TestAPIMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      ResourceId: !Ref TestAPIResource
      HttpMethod: GET
      RestApiId: !Ref TestAPI
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref TestAPIAuthorizer



